### ISSUE TITLE
Pom: Appium dependency uses incompatible version of org.seleniumhq.selenium

### ISSUE THREAD

**Issue by g-kozinets** [aquality-automation/aquality-appium-mobile-java#28]
Appium dependency has Selenium dependency with version set to 4.0 and higher. Current version of aquality-appium-mobile-java (3.0.0 beta) only works with Selenium 4.1.0.

Problem occurs when trying to start example test from class AndroidBasicInteractionsTest. Test throws exception:

> java.lang.NoSuchMethodError: 'void org.openqa.selenium.support.ui.WebDriverWait.<init>(org.openqa.selenium.WebDriver, long)'

Workaround: Add Selenium dependency with 4.1.0 version to aquality-appium-mobile pom
